language: java
sudo: false # faster builds
jdk:
  - openjdk8
  - openjdk11
node_js: "10"
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - node_modules
before_script:
  - npm install
# see details https://github.com/codecov/example-java-maven
script:
  - mvn cobertura:cobertura

install: travis_wait 30 ./mvnw clean install -Dmaven.javadoc.skip=true -Dgpg.skip=true -DskipNpmBuild=true -Dmaven.test.skip=true
# report to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - jnyuqy@gmail.com
