language: java
jdk:
  - openjdk8
node_js: "10"
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
    - node_modules
before_script:
  - npm install
script: travis_wait 30 ./mvnw clean install -Dmaven.javadoc.skip=true -Dgpg.skip -DskipNpmBuild=true -Dmaven.test.skip=true
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - jnyuqy@gmail.com
