spring:
  application:
    name: api-boot-sample-security-oauth-jwt
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
api:
  boot:
    security:
      # Spring Security 内存方式用户列表示例
      users:
        - username: hengboy
          password: 123456
        - username: apiboot
          password: abc321
    oauth:
      jwt:
        # 开启Jwt转换AccessToken
        enable: true
        # 转换Jwt时所需加密key，默认为ApiBoot
        sign-key: 恒宇少年 - 于起宇
      away: jdbc
